### ISSUE TITLE
plugin not found? 

### ISSUE THREAD

**Issue by apredeus** [bhofmei/jbplugin-hierarchicalcheckbox#5]
Hello Brigitte, 

thank you for the plugin - it seems to be just what I need for my datasets! However, I'm having trouble installing it. I've followed the instructions with JBrowse 1.15.4 (cloned the repo into /plugins, added the lines to jbrowse.conf), but adding the necessary lines to just makes it error out with the following message: 

> plugin HierarchicalCheckboxPlugin not found, please ensure the plugin was included in this JBrowse build. 

I'm using a dataset selector option, if that's of any consequence. Thank you!

**Comment by bhofmei** [comment]
That’s annoying. I haven’t tested it with JBrowse 1.15.4. In the past, this would mainly happen if the plugin file wasn’t renamed and/or the location wasn’t specified in the jbrowse.conf file. I’ll look into it.

Do you have other plugins (besides the ones JBrowse comes with) that are working?

**Comment by apredeus** [comment]
Thanks for looking into this. 

I do have some plugins and they don't seem to cause any problems (even though I can't tell they are definitely working, I don't know what most of them do).

I've re-run ./setup.sh but that doesn't seem to change anything. If I comment out the line from jbrowse.conf everything is back to normal. The name of the folder in the /plugins is also correct, I'm pretty sure.

**Comment by bhofmei** [comment]
Sorry for the delay--holidays and another project.

Sorry in advance this isn't going to a very satisfying answer. So, I've downloaded 1.15.4 and the *only* way I can get any plugins (besides the pre-loaded ones) to work is to use this in the `jbrowse.conf` file
```
[ plugins.HierarchicalCheckboxPlugin ]
location = plugins/HierarchicalCheckboxPlugin
```

The documentation says you can use 
```
plugins += GCContent
```
or 
```
plugins =
    + MyAwesomePlugin
```
Those never even attempt to load the plugin.

When I first tried to test this I did get the error you mention. Ultimately, I redownloaded the release and re-ran `setup.sh` and that fixed it. I'm at a loss otherwise

**Comment by apredeus** [comment]
Thank you for looking into it! I will try it.

**Comment by cmdcolin** [comment]
JBrowse 1.13.0+ requires using a "development build" (either the -dev or a github clone) to use any plugins which is the main reason for  messages like "plugin HierarchicalCheckboxPlugin not found, please ensure the plugin was included in this JBrowse build."

I'm sorry that has caused confusion

**Comment by cmdcolin** [comment]
(sorry for necropost also)
